Updated Dockerfile and Jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,41 +1,74 @@
-pipeline{
-    agent {label 'Frontend'}
+pipeline {
+    agent any
     environment {
-
-        APP_SERVER = "172.31.37.135"
-        DEPLOY_DIR = "/var/www/html"
+        IMAGE_NAME = "gopalsharma2504/frontend-app"
+        IMAGE_TAG  = "${BUILD_NUMBER}"
+        APP_SERVER = "43.204.111.98"
     }
-    stages{
-        
-        stage('Pre Build Actions'){
-            steps{
-                sh 'npm install'
-            }
-        }
-        stage('Build'){
-            steps{
-                sh 'npm run build'
-            }
-        }
-        stage('Post Build Actions'){
+    stages {
+        stage('Checkout') {
             steps {
-
+                git branch: 'main',
+                url: 'https://github.com/gopalkamalsharma/Jenkins-WebApp.git'
+            }
+        }
+        stage('Build Docker Image') {
+            steps {
+                sh '''
+                docker build -f docker/dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
+                '''
+            }
+        }
+        stage('Docker Login') {
+            steps {
+                withCredentials([
+                    usernamePassword(
+                        credentialsId: 'DockerCred',
+                        usernameVariable: 'DOCKER_USER',
+                        passwordVariable: 'DOCKER_PASS'
+                    )
+                ]) {
+                    sh '''
+                    echo $DOCKER_PASS | docker login \
+                    -u $DOCKER_USER \
+                    --password-stdin
+                    '''
+                }
+            }
+        }
+        stage('Push Image') {
+            steps {
+                sh '''
+                docker push $IMAGE_NAME:$IMAGE_TAG
+                docker tag \
+                $IMAGE_NAME:$IMAGE_TAG \
+                $IMAGE_NAME:latest
+                docker push $IMAGE_NAME:latest
+                '''
+            }
+        }
+        stage('Deploy To App Server') {
+            steps {
                 sh """
-
-                echo 'Cleaning old files on app server'
-
-                ssh jenkins@${APP_SERVER} 'rm -rf ${DEPLOY_DIR}/*'
-
-                echo 'Copying frontend build'
-
-                scp -r dist/* jenkins@${APP_SERVER}:${DEPLOY_DIR}/
-
-                echo 'Restarting nginx'
-
-                ssh jenkins@${APP_SERVER} 'sudo systemctl restart nginx'
-
+                ssh ubuntu@$APP_SERVER '
+                docker pull $IMAGE_NAME:latest
+                docker stop frontend || true
+                docker rm frontend || true
+                docker run -d \
+                --name frontend \
+                -p 80:80 \
+                $IMAGE_NAME:latest
+                '
                 """
             }
+        }
+    }
+    post {
+        success {
+            echo "Deployment Successful"
+        }
+        failure {
+            echo "Deployment Failed"
         }
     }
 }
