EKS Deployment

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -4,12 +4,11 @@ pipeline{
         AWS_REGION = 'ap-south-1'
         ACCOUNT_ID = '239857123300'
         REPOSITORY = 'frontend'
-        IMAGE_TAG = '${BUILD_NUMBER}'
+        IMAGE_TAG = "${BUILD_NUMBER}"
         ECR_URI = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPOSITORY}"
         EKS_CLUSTER = 'demo-cluster'
         SERVICE_NAME = 'frontend'
         K8S_NAMESPACE = 'development'
-        IMAGE_URI
     }
     stages{
         stage('Checkout'){
@@ -28,10 +27,6 @@ pipeline{
         stage('Login to AWS ECR'){
             steps {
                     sh """
-                        export AWS_DEFAULT_REGION=${AWS_REGION}
-
-                        aws sts get-caller-identity
-
                         aws ecr get-login-password --region ${AWS_REGION} | \
                         docker login \
                         --username AWS \
@@ -39,14 +34,13 @@ pipeline{
                     """
                 }
             }
-        }
         
         stage('Tag and Push Docker Image to ECR'){
             steps{
                 sh """
-                docker tag ${REPOSITORY}:${IMAGE_TAG} ${ECR_URI}
+                docker tag ${REPOSITORY}:${IMAGE_TAG} ${ECR_URI}:${IMAGE_TAG}
                 docker tag ${REPOSITORY}:${IMAGE_TAG} ${ECR_URI}:latest
-                docker push ${ECR_URI}
+                docker push ${ECR_URI}:${IMAGE_TAG}
                 docker push ${ECR_URI}:latest
                 """
             }
@@ -62,7 +56,7 @@ pipeline{
         stage('Deploy to EKS Service'){
             steps{
                 sh """
-                kubectl set image deployment/${SERVICE_NAME} ${SERVICE_NAME}=${ECR_URI}:${IMAGE_TAG} --record
+                kubectl set image deployment/frontend frontend=image
                 kubectl rollout status deployment/${SERVICE_NAME} -n ${K8S_NAMESPACE} --timeout=300s;
                 """
             }
@@ -73,25 +67,38 @@ pipeline{
                 kubectl get pods -n ${K8S_NAMESPACE}
                 kubectl get svc -n ${K8S_NAMESPACE}
                 kubectl get ingress -n ${K8S_NAMESPACE}
+                kubectl get replicaset -n ${K8S_NAMESPACE}
+                kubectl get endpoints -n ${K8S_NAMESPACE}
                 kubectl get deployment -n ${K8S_NAMESPACE}
                 """
             }
         }
     }
     post{
-        success{
-            echo "Deployment Successful!"
-            cleanWs()
-            sh 'docker image prune -f'
-        }
-        failure{
-            echo "Deployment Failed!"
-            cleanWs()
+        always {
+
             sh '''
-            docker image prune -f
-            kubectl rollout undo deployment/${SERVICE_NAME} -n ${K8S_NAMESPACE}
+                docker image prune -af || true
             '''
-            echo "Rolled back to previous deployment"
+
+            cleanWs()
+
+        }
+        success {
+
+            echo "Deployment Successful"
+
+        }
+        failure {
+
+            echo "Deployment Failed"
+
+            sh """
+                kubectl rollout undo deployment/${SERVICE_NAME} -n ${K8S_NAMESPACE} || true
+
+                docker image prune -af || true
+            """
+
         }
     }
 }
